In [1]:
# Imports

import pandas as pd
import numpy as np

In [3]:
# Load Flight Dataset

flights_df = pd.read_csv(
    "../data/raw/Flight Price Prediction/Clean_Dataset.csv"
)

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

In [4]:
# Preview Dataset
flights_df.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [38]:
# Understand Dataset Colume
flights_df.columns

Index(['airline', 'flight', 'from_city', 'departure_time', 'stops',
       'arrival_time', 'to_city', 'class', 'duration', 'days_left', 'price'],
      dtype='str')

### NEXT STEP → Clean the Dataset

We will:

* remove useless column
* rename columns professionally
* prepare it for AI flight search

In [6]:
# Remove Unnecessary Column
# Remove unnecessary column

flights_df = flights_df.drop(
    columns=["Unnamed: 0"]
)

flights_df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [7]:
# Check Dataset Info
flights_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  str
 1   flight            300153 non-null  str
 2   source_city       300153 non-null  str
 3   departure_time    300153 non-null  str
 4   stops             300153 non-null  str
 5   arrival_time      300153 non-null  str
 6   destination_city  300153 non-null  str
 7   class             300153 non-null  str
 8   duration          300153 non-null  float64
 9   days_left         300153 non-null  int64
 10  price             300153 non-null  int64
dtypes: float64(1), int64(2), str(8)
memory usage: 40.6 MB

In [8]:
# Rename Columns Professionally
# Rename columns

flights_df = flights_df.rename(
    columns={
        "source_city": "from_city",
        "destination_city": "to_city"
    }
)

flights_df.head()

,airline,flight,from_city,departure_time,stops,arrival_time,to_city,class,duration,days_left,price
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [9]:
# View Unique Cities
# Available Cities

print(flights_df["from_city"].unique())

print()

print(flights_df["to_city"].unique())

<ArrowStringArray>
['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai']
Length: 6, dtype: str

<ArrowStringArray>
['Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai', 'Delhi']
Length: 6, dtype: str

In [10]:
# View Airlines
# Available Airlines

flights_df["airline"].unique()

<ArrowStringArray>
['SpiceJet', 'AirAsia', 'Vistara', 'GO_FIRST', 'Indigo', 'Air_India']
Length: 6, dtype: str

In [47]:
# Flight Search Function

# Advanced Flight Search Function

def search_flights(
    from_city,
    to_city,
    travel_class,
    departure_time=None,
    max_price=None
):

    filtered_df = flights_df[

        (flights_df["from_city"].str.lower() == from_city.lower()) &

        (flights_df["to_city"].str.lower() == to_city.lower()) &

        (flights_df["class"].str.lower() == travel_class.lower())

    ]

    # Time filtering

    if departure_time:

        filtered_df = filtered_df[

            filtered_df["departure_time"].str.lower()
            ==
            departure_time.lower()

        ]

    # Budget filtering

    if max_price:

        filtered_df = filtered_df[
            filtered_df["price"] <= max_price
        ]

    # Cheapest flights first

    filtered_df = filtered_df.sort_values(
        by="price"
    )

    return filtered_df.head(5)

In [48]:
# Test Flight Search
search_flights(
    from_city="Delhi",
    to_city="Mumbai",
    travel_class="Economy"
)

,airline,flight,from_city,departure_time,stops,arrival_time,to_city,class,duration,days_left,price
9377,SpiceJet,SG-8723,Delhi,Morning,zero,Morning,Mumbai,Economy,2.17,47,2281
9378,SpiceJet,SG-8701,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.25,47,2281
9379,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.33,47,2281
9380,SpiceJet,SG-8169,Delhi,Evening,zero,Night,Mumbai,Economy,2.33,47,2281
9179,Indigo,6E-2168,Delhi,Evening,one,Night,Mumbai,Economy,4.50,46,2381

In [49]:
# Test Morning Flights
search_flights(
    from_city="Delhi",
    to_city="Mumbai",
    travel_class="Economy",
    departure_time="Morning"
)

,airline,flight,from_city,departure_time,stops,arrival_time,to_city,class,duration,days_left,price
9377,SpiceJet,SG-8723,Delhi,Morning,zero,Morning,Mumbai,Economy,2.17,47,2281
8793,AirAsia,I5-1529,Delhi,Morning,one,Late_Night,Mumbai,Economy,15.00,44,2409
8787,AirAsia,I5-1529,Delhi,Morning,one,Night,Mumbai,Economy,11.00,44,2409
5995,AirAsia,I5-1529,Delhi,Morning,one,Night,Mumbai,Economy,11.00,31,2409
6001,AirAsia,I5-1529,Delhi,Morning,one,Late_Night,Mumbai,Economy,15.00,31,2409

In [84]:
# Create Ticket Booking Function
# Ticket Booking Function

import random

def book_ticket(

    passenger_name,
    from_city,
    to_city,
    airline,
    travel_class,
    departure_time,
    travel_date,
    seat_preference,
    price

):

    ticket_id = f"AI-{random.randint(10000,99999)}"

    # Seat Logic
    if seat_preference.lower() == "window":
        seat_letter = random.choice(["A", "F"])

    elif seat_preference.lower() == "aisle":
        seat_letter = random.choice(["C", "D"])

    else:
        seat_letter = random.choice(["B", "E"])

    seat_number = f"{random.randint(1,30)}{seat_letter}"

    ticket = {

        "ticket_id": ticket_id,

        "passenger_name": passenger_name,

        "from_city": from_city,

        "to_city": to_city,

        "airline": airline,

        "travel_class": travel_class,

        "departure_time": departure_time,

        "travel_date": travel_date,

        "seat_preference": seat_preference,

        "seat_number": seat_number,

        "price": price,

        "booking_status": "CONFIRMED"

    }

    return ticket

In [89]:
# Test Ticket Booking
book_ticket(
    passenger_name="Jayant",
    from_city="Delhi",
    to_city="Mumbai",
    travel_class="Economy"
)

TypeError: book_ticket() missing 5 required positional arguments: 'airline', 'departure_time', 'travel_date', 'seat_preference', and 'price'

In [86]:
#Create Flight Search Tool
# Flight Search Tool

flight_search_tool = {

    "type": "function",

    "function": {

        "name": "search_flights",

        "description": "Search available airline flights",

        "parameters": {

            "type": "object",

            "properties": {

                "from_city": {
                    "type": "string",
                    "description": "Departure city"
                },

                "to_city": {
                    "type": "string",
                    "description": "Destination city"
                },

                "travel_class": {
                    "type": "string",
                    "description": "Flight class like Economy or Business"
                },

                "departure_time": {
                    "type": "string",
                    "description": "Preferred departure timing like Morning, Evening, Night"
                },

                "max_price": {
                    "type": "integer",
                    "description": "Maximum ticket budget"
                }

            },

            "required": [
                "from_city",
                "to_city",
                "travel_class"
            ]

        }
    }
}

In [92]:
# Create Booking Tool
# Ticket Booking Tool

ticket_booking_tool = {

    "type": "function",

    "function": {

        "name": "book_ticket",

        "description": "Book airline ticket for passenger",

        "parameters": {

            "type": "object",

            "properties": {

                "passenger_name": {
                    "type": "string",
                    "description": "Passenger full name"
                },

                "from_city": {
                    "type": "string",
                    "description": "Departure city"
                },

                "to_city": {
                    "type": "string",
                    "description": "Destination city"
                },

                "travel_class": {
                    "type": "string",
                    "description": "Travel class"
                }

            },

            "required": [
                "passenger_name",
                "from_city",
                "to_city",
                "travel_class"
            ]
        }
    }
}

In [93]:
# Combine Tools
# Combine Tools

tools = [
    flight_search_tool,
    ticket_booking_tool
]

print("Tools Ready!")

Tools Ready!

In [94]:
response = client.chat.completions.create(

    model=MODEL,

    messages=[

        {
            "role": "system",

            "content": """
            You are an intelligent airline booking assistant.

            Always use tools for ticket booking.
            """
        },

        {
            "role": "user",

            "content": """
            Book a morning economy ticket
            from Delhi to Mumbai

            Passenger: Rahul Sharma
            Airline: Air India
            Travel Date: 25 June 2026
            Seat Preference: Window
            Budget: 6000
            """
        }

    ],

    tools=tools,
    tool_choice="auto"

)

response

ChatCompletion(id='gen-1779457769-NGj6cmYqvoicqrUnOp3s', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_uTCTYCiq5uOPoNMCsQqfZcWM', function=Function(arguments='{"from_city":"Delhi","to_city":"Mumbai","travel_class":"Economy","departure_time":"Morning","max_price":6000}', name='search_flights'), type='function', index=0)], reasoning=None), native_finish_reason='tool_calls')], created=1779457769, model='openai/gpt-4o-mini', object='chat.completion', service_tier=None, system_fingerprint='fp_e79d02e4a2', usage=CompletionUsage(completion_tokens=38, prompt_tokens=213, total_tokens=251, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=0, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=5.475e-05, is_byok=False, cost_details={'upstream_inference_cost': 5.475e-05, 'upstream_inference_prompt_cost': 3.195e-05, 'upstream_inference_completions_cost': 2.28e-05}), provider='OpenAI')

In [53]:
response = client.chat.completions.create(

    model=MODEL,

    messages=[

        {
            "role": "user",
            "content": """
            Find me morning economy flights 
            from Delhi to Mumbai 
            under 6000 rupees
            """
        }

    ],

    tools=tools
)

response

ChatCompletion(id='gen-1779451455-zODg9Tr957Lhq3uzDCDJ', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_8VTqPlB1Ee6HOyjkIiC7nFk4', function=Function(arguments='{"from_city":"Delhi","to_city":"Mumbai","travel_class":"Economy","departure_time":"Morning","max_price":6000}', name='search_flights'), type='function', index=0)], reasoning=None), native_finish_reason='tool_calls')], created=1779451455, model='openai/gpt-4o-mini', object='chat.completion', service_tier=None, system_fingerprint='fp_c2f5782bd4', usage=CompletionUsage(completion_tokens=38, prompt_tokens=166, total_tokens=204, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=0, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=4.77e-05, is_byok=False, cost_details={'upstream_inference_cost': 4.77e-05, 'upstream_inference_prompt_cost': 2.49e-05, 'upstream_inference_completions_cost': 2.28e-05}), provider='OpenAI')

In [22]:
from openai import OpenAI
from dotenv import load_dotenv
import os

load_dotenv()

client = OpenAI(
    api_key=os.getenv("OPENROUTER_API_KEY"),
    base_url="https://openrouter.ai/api/v1"
)

MODEL = "openai/gpt-4o-mini"

In [25]:
# First AI Flight Booking Test
# AI Booking Request

response = client.chat.completions.create(

    model=MODEL,

    messages=[

        {
            "role": "system",

            "content": """
            You are an intelligent airline booking assistant.

            Help users:
            - search flights
            - compare prices
            - book tickets

            Use tools whenever needed.
            """
        },

        {
            "role": "user",

            "content": """
            Find me economy flights from Delhi to Mumbai
            """
        }
    ],

    tools=tools
)

response

ChatCompletion(id='gen-1779438514-6xN5gUozlmj0mgcxWUUI', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_215gAcEps6KTcmlTTX9rMynB', function=Function(arguments='{"from_city":"Delhi","to_city":"Mumbai","travel_class":"Economy"}', name='search_flights'), type='function', index=0)], reasoning=None), native_finish_reason='tool_calls')], created=1779438514, model='openai/gpt-4o-mini', object='chat.completion', service_tier=None, system_fingerprint='fp_5334d4fbca', usage=CompletionUsage(completion_tokens=27, prompt_tokens=168, total_tokens=195, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=0, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=4.14e-05, is_byok=False, cost_details={'upstream_inference_cost': 4.14e-05, 'upstream_inference_prompt_cost': 2.52e-05, 'upstream_inference_completions_cost': 1.62e-05}), provider='OpenAI')

In [26]:
# Extract AI Message

message = response.choices[0].message

message

ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_215gAcEps6KTcmlTTX9rMynB', function=Function(arguments='{"from_city":"Delhi","to_city":"Mumbai","travel_class":"Economy"}', name='search_flights'), type='function', index=0)], reasoning=None)

In [27]:
# Check Tool Calls

message.tool_calls

[ChatCompletionMessageFunctionToolCall(id='call_215gAcEps6KTcmlTTX9rMynB', function=Function(arguments='{"from_city":"Delhi","to_city":"Mumbai","travel_class":"Economy"}', name='search_flights'), type='function', index=0)]

In [29]:
import json

In [30]:
# Execute Tool

tool_call = message.tool_calls[0]

tool_args = json.loads(
    tool_call.function.arguments
)

tool_args

{'from_city': 'Delhi', 'to_city': 'Mumbai', 'travel_class': 'Economy'}

In [31]:
# Run Flight Search Tool

results = search_flights(
    from_city=tool_args["from_city"],
    to_city=tool_args["to_city"],
    travel_class=tool_args["travel_class"]
)

results

============================================================
✈️ Airline      : SpiceJet
🛫 Flight       : SG-8709
📍 From         : Delhi
📍 To           : Mumbai
🕒 Departure    : Evening
🕓 Arrival      : Night
⏳ Duration     : 2.17
🛑 Stops        : zero
💺 Class        : Economy
💰 Price        : ₹5953
============================================================
============================================================
✈️ Airline      : SpiceJet
🛫 Flight       : SG-8157
📍 From         : Delhi
📍 To           : Mumbai
🕒 Departure    : Early_Morning
🕓 Arrival      : Morning
⏳ Duration     : 2.33
🛑 Stops        : zero
💺 Class        : Economy
💰 Price        : ₹5953
============================================================
============================================================
✈️ Airline      : AirAsia
🛫 Flight       : I5-764
📍 From         : Delhi
📍 To           : Mumbai
🕒 Departure    : Early_Morning
🕓 Arrival      : Early_Morning
⏳ Duration     : 2.17
🛑 Stops        : zero
💺 Class        : Economy
💰 Price        : ₹5956
============================================================
============================================================
✈️ Airline      : Vistara
🛫 Flight       : UK-995
📍 From         : Delhi
📍 To           : Mumbai
🕒 Departure    : Morning
🕓 Arrival      : Afternoon
⏳ Duration     : 2.25
🛑 Stops        : zero
💺 Class        : Economy
💰 Price        : ₹5955
============================================================
============================================================
✈️ Airline      : Vistara
🛫 Flight       : UK-963
📍 From         : Delhi
📍 To           : Mumbai
🕒 Departure    : Morning
🕓 Arrival      : Morning
⏳ Duration     : 2.33
🛑 Stops        : zero
💺 Class        : Economy
💰 Price        : ₹5955
============================================================

In [34]:
# Run Flight Search Tool

results = search_flights(
    from_city=tool_args["from_city"],
    to_city=tool_args["to_city"],
    travel_class=tool_args["travel_class"]
)

results

============================================================
✈️ Airline      : SpiceJet
🛫 Flight       : SG-8709
📍 From         : Delhi
📍 To           : Mumbai
🕒 Departure    : Evening
🕓 Arrival      : Night
⏳ Duration     : 2.17
🛑 Stops        : zero
💺 Class        : Economy
💰 Price        : ₹5953
============================================================
============================================================
✈️ Airline      : SpiceJet
🛫 Flight       : SG-8157
📍 From         : Delhi
📍 To           : Mumbai
🕒 Departure    : Early_Morning
🕓 Arrival      : Morning
⏳ Duration     : 2.33
🛑 Stops        : zero
💺 Class        : Economy
💰 Price        : ₹5953
============================================================
============================================================
✈️ Airline      : AirAsia
🛫 Flight       : I5-764
📍 From         : Delhi
📍 To           : Mumbai
🕒 Departure    : Early_Morning
🕓 Arrival      : Early_Morning
⏳ Duration     : 2.17
🛑 Stops        : zero
💺 Class        : Economy
💰 Price        : ₹5956
============================================================
============================================================
✈️ Airline      : Vistara
🛫 Flight       : UK-995
📍 From         : Delhi
📍 To           : Mumbai
🕒 Departure    : Morning
🕓 Arrival      : Afternoon
⏳ Duration     : 2.25
🛑 Stops        : zero
💺 Class        : Economy
💰 Price        : ₹5955
============================================================
============================================================
✈️ Airline      : Vistara
🛫 Flight       : UK-963
📍 From         : Delhi
📍 To           : Mumbai
🕒 Departure    : Morning
🕓 Arrival      : Morning
⏳ Duration     : 2.33
🛑 Stops        : zero
💺 Class        : Economy
💰 Price        : ₹5955
============================================================

In [43]:
results = search_flights(
    from_city="Delhi",
    to_city="Mumbai",
    travel_class="Economy"
)

In [ ]:
# Convert results:
results_text = ""

for i, row in results.iterrows():

    results_text += f"""
Flight: {row['airline']}
From: {row['from_city']}
To: {row['to_city']}
Class: {row['class']}
Price: ₹{row['price']}
Duration: {row['duration']}
Stops: {row['stops']}
Departure: {row['departure_time']}
Arrival: {row['arrival_time']}

==========================
"""
    
print(results_text)

Flight: SpiceJet
From: Delhi
To: Mumbai
Class: Economy
Price: ₹2281
Duration: 2.17
Stops: zero
Departure: Morning
Arrival: Morning

==========================

Flight: SpiceJet
From: Delhi
To: Mumbai
Class: Economy
Price: ₹2281
Duration: 2.25
Stops: zero
Departure: Early_Morning
Arrival: Morning

==========================

Flight: SpiceJet
From: Delhi
To: Mumbai
Class: Economy
Price: ₹2281
Duration: 2.33
Stops: zero
Departure: Evening
Arrival: Night

==========================

Flight: SpiceJet
From: Delhi
To: Mumbai
Class: Economy
Price: ₹2281
Duration: 2.33
Stops: zero
Departure: Evening
Arrival: Night

==========================

Flight: Indigo
From: Delhi
To: Mumbai
Class: Economy
Price: ₹2381
Duration: 4.5
Stops: one
Departure: Evening
Arrival: Night

==========================

In [45]:
# Send results back to AI:
final_response = client.chat.completions.create(

    model=MODEL,

    messages=[

        {
            "role": "system",
            "content": """
            You are an intelligent airline booking assistant.
            Recommend flights professionally.
            """
        },

        {
            "role": "user",
            "content": "Find me economy flights from Delhi to Mumbai"
        },

        message,

        {
            "role": "tool",
            "tool_call_id": tool_call.id,
            "content": results_text
        }

    ]
)

print(final_response.choices[0].message.content)

Here are some economy flight options from Delhi to Mumbai:

1. **SpiceJet**
   - **Price:** ₹2281
   - **Duration:** 2 hours 10 minutes
   - **Stops:** Non-stop
   - **Departure:** Morning
   - **Arrival:** Morning

2. **SpiceJet**
   - **Price:** ₹2281
   - **Duration:** 2 hours 15 minutes
   - **Stops:** Non-stop
   - **Departure:** Early Morning
   - **Arrival:** Morning

3. **SpiceJet**
   - **Price:** ₹2281
   - **Duration:** 2 hours 20 minutes
   - **Stops:** Non-stop
   - **Departure:** Evening
   - **Arrival:** Night

4. **SpiceJet**
   - **Price:** ₹2281
   - **Duration:** 2 hours 20 minutes
   - **Stops:** Non-stop
   - **Departure:** Evening
   - **Arrival:** Night

5. **Indigo**
   - **Price:** ₹2381
   - **Duration:** 4 hours 30 minutes
   - **Stops:** One stop
   - **Departure:** Evening
   - **Arrival:** Night

For the best experience, I recommend the non-stop flights with SpiceJet, which offer shorter durations. Would you like more details about any specific flight or assistance with your booking?

In [46]:
# Understand Time Values
flights_df["departure_time"].unique()

<ArrowStringArray>
['Evening', 'Early_Morning', 'Morning', 'Afternoon', 'Night', 'Late_Night']
Length: 6, dtype: str

### Create Booking Function

In [54]:
# Ticket Booking Function

def book_ticket(

    passenger_name,
    from_city,
    to_city,
    airline,
    travel_class,
    departure_time,
    price

):

    ticket = {

        "passenger_name": passenger_name,
        "from_city": from_city,
        "to_city": to_city,
        "airline": airline,
        "travel_class": travel_class,
        "departure_time": departure_time,
        "price": price,
        "booking_status": "CONFIRMED"

    }

    return ticket

In [70]:
# Ticket Booking Tool

ticket_booking_tool = {

    "type": "function",

    "function": {

        "name": "book_ticket",

        "description": "Book airline tickets",

        "parameters": {

            "type": "object",

            "properties": {

                "passenger_name": {
                    "type": "string",
                    "description": "Full name of passenger"
                },

                "from_city": {
                    "type": "string",
                    "description": "Departure city"
                },

                "to_city": {
                    "type": "string",
                    "description": "Destination city"
                },

                "airline": {
                    "type": "string",
                    "description": "Preferred airline"
                },

                "travel_class": {
                    "type": "string",
                    "description": "Travel class like Economy or Business"
                },

                "departure_time": {
                    "type": "string",
                    "description": "Preferred departure timing like Morning or Evening"
                },

                "travel_date": {
                    "type": "string",
                    "description": "Travel date for the flight"
                },

                "price": {
                    "type": "integer",
                    "description": "Ticket budget or selected ticket price"
                }

            },

            "required": [

                "passenger_name",
                "from_city",
                "to_city",
                "airline",
                "travel_class",
                "departure_time",
                "travel_date",
                "price"

            ]

        }
    }
}

In [71]:
# Combine Tools
tools = [

    flight_search_tool,

    ticket_booking_tool

]

print("Tools Ready!")

Tools Ready!

In [59]:
# Test Booking Request
response = client.chat.completions.create(

    model=MODEL,

    messages=[

        {
            "role": "system",

            "content": """
            You are an airline booking assistant.

            ALWAYS use tools for:
            - searching flights
            - booking tickets

            Never answer directly.
            """
        },

        {
            "role": "user",

            "content": """
            Book a morning economy ticket
            from Delhi to Mumbai
            for Rahul Sharma

            Use Air India
            Budget under 6000
            """
        }

    ],

    tools=tools,
    tool_choice="auto"

)

response

ChatCompletion(id='gen-1779451776-R6h4J3R01mOMlUpkOze5', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_iCc5f5INBxCVnfDGFUBPA338', function=Function(arguments='{"from_city":"Delhi","to_city":"Mumbai","travel_class":"Economy","departure_time":"Morning","max_price":6000}', name='search_flights'), type='function', index=0)], reasoning=None), native_finish_reason='tool_calls')], created=1779451776, model='openai/gpt-4o-mini', object='chat.completion', service_tier=None, system_fingerprint='fp_f8d40babb7', usage=CompletionUsage(completion_tokens=38, prompt_tokens=202, total_tokens=240, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=0, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=5.31e-05, is_byok=False, cost_details={'upstream_inference_cost': 5.31e-05, 'upstream_inference_prompt_cost': 3.03e-05, 'upstream_inference_completions_cost': 2.28e-05}), provider='OpenAI')

In [60]:
# Extract Message
message = response.choices[0].message

message.tool_calls

[ChatCompletionMessageFunctionToolCall(id='call_iCc5f5INBxCVnfDGFUBPA338', function=Function(arguments='{"from_city":"Delhi","to_city":"Mumbai","travel_class":"Economy","departure_time":"Morning","max_price":6000}', name='search_flights'), type='function', index=0)]

In [61]:
# Extract Tool Call
tool_call = message.tool_calls[0]

tool_call

ChatCompletionMessageFunctionToolCall(id='call_iCc5f5INBxCVnfDGFUBPA338', function=Function(arguments='{"from_city":"Delhi","to_city":"Mumbai","travel_class":"Economy","departure_time":"Morning","max_price":6000}', name='search_flights'), type='function', index=0)

In [62]:
# Extract Arguments
tool_args = json.loads(
    tool_call.function.arguments
)

tool_args

{'from_city': 'Delhi',
 'to_city': 'Mumbai',
 'travel_class': 'Economy',
 'departure_time': 'Morning',
 'max_price': 6000}

In [65]:
results = search_flights(

    from_city=tool_args["from_city"],

    to_city=tool_args["to_city"],

    travel_class=tool_args["travel_class"]

)

results.head()

,airline,flight,from_city,departure_time,stops,arrival_time,to_city,class,duration,days_left,price
9377,SpiceJet,SG-8723,Delhi,Morning,zero,Morning,Mumbai,Economy,2.17,47,2281
9378,SpiceJet,SG-8701,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.25,47,2281
9379,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.33,47,2281
9380,SpiceJet,SG-8169,Delhi,Evening,zero,Night,Mumbai,Economy,2.33,47,2281
9179,Indigo,6E-2168,Delhi,Evening,one,Night,Mumbai,Economy,4.50,46,2381

In [66]:
results_text = ""

for i, row in results.head(5).iterrows():

    results_text += f"""

Flight {i+1}

Airline: {row['airline']}
From: {row['from_city']}
To: {row['to_city']}
Class: {row['class']}
Departure: {row['departure_time']}
Arrival: {row['arrival_time']}
Duration: {row['duration']}
Price: ₹{row['price']}

"""

In [68]:
final_response = client.chat.completions.create(

    model=MODEL,

    messages=[

        {
            "role": "system",

            "content": """
            You are an AI airline booking assistant.

            Recommend the best available flights
            based on user preferences.
            """
        },

        {
            "role": "user",

            "content": f"""

            User Request:
            Economy flights from Delhi to Mumbai
            under 6000 rupees.

            Available Flights:

            {results_text}

            Recommend the best 3 flights.
            """

        }

    ]

)

print(final_response.choices[0].message.content)

Here are the best 3 available economy flights from Delhi to Mumbai under ₹6000:

1. **Flight 9378**
   - **Airline:** SpiceJet
   - **Departure:** Morning
   - **Arrival:** Morning
   - **Duration:** 2 hours 17 minutes
   - **Price:** ₹2281

2. **Flight 9379**
   - **Airline:** SpiceJet
   - **Departure:** Early Morning
   - **Arrival:** Morning
   - **Duration:** 2 hours 25 minutes
   - **Price:** ₹2281

3. **Flight 9380**
   - **Airline:** SpiceJet
   - **Departure:** Evening
   - **Arrival:** Night
   - **Duration:** 2 hours 33 minutes
   - **Price:** ₹2281

All of these flights are well within your budget and offer convenient timings. Let me know if you need further assistance!

In [72]:
# Test New Booking Prompt
response = client.chat.completions.create(

    model=MODEL,

    messages=[

        {
            "role": "system",

            "content": """
            You are an AI airline booking assistant.

            Always use tools for booking.
            """
        },

        {
            "role": "user",

            "content": """
            Book a morning economy ticket
            from Delhi to Mumbai

            Passenger: Rahul Sharma
            Airline: Air India
            Travel Date: 25 June 2026
            Budget: 6000
            """
        }

    ],

    tools=tools,
    tool_choice="auto"

)

response

ChatCompletion(id='gen-1779453472-cmIp0LVm5TfUQNruFNFj', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_pa744bbSat4CA5zCmTP5hMxq', function=Function(arguments='{"from_city":"Delhi","to_city":"Mumbai","travel_class":"Economy","departure_time":"Morning","max_price":6000}', name='search_flights'), type='function', index=0)], reasoning=None), native_finish_reason='tool_calls')], created=1779453472, model='openai/gpt-4o-mini', object='chat.completion', service_tier=None, system_fingerprint='fp_e3286cfe02', usage=CompletionUsage(completion_tokens=38, prompt_tokens=252, total_tokens=290, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=0, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=6.06e-05, is_byok=False, cost_details={'upstream_inference_cost': 6.06e-05, 'upstream_inference_prompt_cost': 3.78e-05, 'upstream_inference_completions_cost': 2.28e-05}), provider='OpenAI')

In [73]:
# Test New Booking Prompt
response = client.chat.completions.create(

    model=MODEL,

    messages=[

        {
            "role": "system",

            "content": """
            You are an AI airline booking assistant.

            Always use tools for booking.
            """
        },

        {
            "role": "user",

            "content": """
            Book a morning economy ticket
            from Delhi to Mumbai

            Passenger: Rahul Sharma
            Airline: Air India
            Travel Date: 25 June 2026
            Budget: 6000
            """
        }

    ],

    tools=tools,
    tool_choice="auto"

)

response

ChatCompletion(id='gen-1779453525-JBqsWt1Vnvx8n7YCc26h', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_x45zyK5i8Oi0eJQpR1ZmqVMj', function=Function(arguments='{"from_city":"Delhi","to_city":"Mumbai","travel_class":"Economy","departure_time":"Morning","max_price":6000}', name='search_flights'), type='function', index=0)], reasoning=None), native_finish_reason='tool_calls')], created=1779453525, model='openai/gpt-4o-mini', object='chat.completion', service_tier=None, system_fingerprint='fp_e3286cfe02', usage=CompletionUsage(completion_tokens=38, prompt_tokens=252, total_tokens=290, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=0, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=6.06e-05, is_byok=False, cost_details={'upstream_inference_cost': 6.06e-05, 'upstream_inference_prompt_cost': 3.78e-05, 'upstream_inference_completions_cost': 2.28e-05}), provider='OpenAI')

In [74]:
# Extract Tool Args
message = response.choices[0].message

tool_call = message.tool_calls[0]

tool_args = json.loads(
    tool_call.function.arguments
)

tool_args

{'from_city': 'Delhi',
 'to_city': 'Mumbai',
 'travel_class': 'Economy',
 'departure_time': 'Morning',
 'max_price': 6000}

In [80]:
results = search_flights(

    from_city=tool_args["from_city"],

    to_city=tool_args["to_city"],

    travel_class=tool_args["travel_class"],

    departure_time=tool_args.get("departure_time"),

    max_price=tool_args.get("max_price")

)

results.head()

,airline,flight,from_city,departure_time,stops,arrival_time,to_city,class,duration,days_left,price
9377,SpiceJet,SG-8723,Delhi,Morning,zero,Morning,Mumbai,Economy,2.17,47,2281
9813,AirAsia,I5-1529,Delhi,Morning,one,Late_Night,Mumbai,Economy,15.00,49,2409
9207,AirAsia,I5-1529,Delhi,Morning,one,Night,Mumbai,Economy,11.00,46,2409
9807,AirAsia,I5-1529,Delhi,Morning,one,Night,Mumbai,Economy,11.00,49,2409
9213,AirAsia,I5-1529,Delhi,Morning,one,Late_Night,Mumbai,Economy,15.00,46,2409

In [81]:
selected_flight = results.iloc[0]

selected_flight

airline           SpiceJet
flight             SG-8723
from_city            Delhi
departure_time     Morning
stops                 zero
arrival_time       Morning
to_city             Mumbai
class              Economy
duration              2.17
days_left               47
price                 2281
Name: 9377, dtype: object

In [82]:
booking = book_ticket(

    passenger_name="Rahul Sharma",

    from_city=selected_flight["from_city"],

    to_city=selected_flight["to_city"],

    airline=selected_flight["airline"],

    travel_class=selected_flight["class"],

    departure_time=selected_flight["departure_time"],

    travel_date="25 June 2026",

    price=selected_flight["price"]

)

booking

{'ticket_id': 'AI-32132',
 'passenger_name': 'Rahul Sharma',
 'from_city': 'Delhi',
 'to_city': 'Mumbai',
 'airline': 'SpiceJet',
 'travel_class': 'Economy',
 'departure_time': 'Morning',
 'travel_date': '25 June 2026',
 'seat_number': '    7    C    ',
 'price': np.int64(2281),
 'booking_status': 'CONFIRMED'}

In [83]:
final_response = client.chat.completions.create(

    model=MODEL,

    messages=[

        {
            "role": "system",

            "content": """
            You are a professional airline booking assistant.

            Confirm ticket bookings professionally.
            """
        },

        {
            "role": "user",

            "content": """
            Book my airline ticket
            """
        },

        {
            "role": "assistant",

            "content": f"""
            Ticket successfully booked.

            Booking Details:

            {booking}
            """
        }

    ]

)

print(final_response.choices[0].message.content)

To assist you with booking your airline ticket, I will need some details:

1. Departure city
2. Destination city
3. Travel date
4. Return date (if applicable)
5. Number of passengers
6. Travel class (Economy, Business, First Class)
7. Any specific preferences or requirements?

Once I have this information, I can help you confirm your ticket booking.

In [ ]:
# Extract Tool Args
message = response.choices[0].message

tool_call = message.tool_calls[0]

tool_args = json.loads(
    tool_call.function.arguments
)

tool_args

{'from_city': 'Delhi',
 'to_city': 'Mumbai',
 'travel_class': 'Economy',
 'departure_time': 'Morning',
 'max_price': 6000}

In [96]:
# Search Flights
results = search_flights(

    from_city=tool_args["from_city"],

    to_city=tool_args["to_city"],

    travel_class=tool_args["travel_class"],

    departure_time=tool_args.get("departure_time"),

    max_price=tool_args.get("max_price")

)

results.head()

,airline,flight,from_city,departure_time,stops,arrival_time,to_city,class,duration,days_left,price
9377,SpiceJet,SG-8723,Delhi,Morning,zero,Morning,Mumbai,Economy,2.17,47,2281
9813,AirAsia,I5-1529,Delhi,Morning,one,Late_Night,Mumbai,Economy,15.00,49,2409
9207,AirAsia,I5-1529,Delhi,Morning,one,Night,Mumbai,Economy,11.00,46,2409
9807,AirAsia,I5-1529,Delhi,Morning,one,Night,Mumbai,Economy,11.00,49,2409
9213,AirAsia,I5-1529,Delhi,Morning,one,Late_Night,Mumbai,Economy,15.00,46,2409

In [97]:
# Select Flight
selected_flight = results.iloc[0]

selected_flight

airline           SpiceJet
flight             SG-8723
from_city            Delhi
departure_time     Morning
stops                 zero
arrival_time       Morning
to_city             Mumbai
class              Economy
duration              2.17
days_left               47
price                 2281
Name: 9377, dtype: object

In [99]:
# Execute Booking
booking = book_ticket(

    passenger_name="Rahul Sharma",

    from_city=selected_flight["from_city"],

    to_city=selected_flight["to_city"],

    airline=selected_flight["airline"],

    travel_class=selected_flight["class"],

    departure_time=selected_flight["departure_time"],

    travel_date="25 June 2026",

    seat_preference="Window",

    price=selected_flight["price"]

)

booking

{'ticket_id': 'AI-31953',
 'passenger_name': 'Rahul Sharma',
 'from_city': 'Delhi',
 'to_city': 'Mumbai',
 'airline': 'SpiceJet',
 'travel_class': 'Economy',
 'departure_time': 'Morning',
 'travel_date': '25 June 2026',
 'seat_preference': 'Window',
 'seat_number': '21F',
 'price': np.int64(2281),
 'booking_status': 'CONFIRMED'}

In [100]:
# Generate Final Confirmation
final_response = client.chat.completions.create(

    model=MODEL,

    messages=[

        {
            "role": "system",

            "content": """
            You are a professional airline booking assistant.

            Confirm bookings professionally.
            """
        },

        {
            "role": "user",

            "content": "Book my ticket"
        },

        {
            "role": "assistant",

            "content": f"""
            Ticket successfully booked.

            Booking Details:

            {booking}
            """
        }

    ]

)

print(final_response.choices[0].message.content)

I can help you with that! Please provide me with the following details:

1. Departure city
2. Destination city
3. Travel date
4. Passenger name
5. Any specific preferences (e.g., window seat, travel class)

Once I have this information, I can assist you with your booking!